# The URL the site will be built for
base_url = "https://lfe.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
default_language = "en"

[link_checker]
internal_level = "warn"

[extra]
# Put all your custom config variables here

[extra.download]

repository = "https://github.com/lfe/lfe"
prior_release = "2.0.1"
current_release = "2.1.4"
pre_release = "refs/heads/develop"
